import { config } from 'dotenv';
config();
export const {
  PORT,
DATABASE_URL,
JWT_SECRET,
JWT_EXPIRES_IN,
FRONTEND_URI,
GITHUB_CLIENT_ID,
GITHUB_CLIENT_SECRET,
CLOUDINARY_URL,
ENV,
BASE_URL_AI,
AI_API_KEY,
TABSCANNER_API_KEY,
TABSCANNER_BASE_URL,
PREFIX_CONTENT,
} = process.env;